# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.1.4"

package:
  name: fps-file-watcher
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fps-file-watcher/fps_file_watcher-${{ version }}.tar.gz
  sha256: ebd0ed2a80938e30f37ba0396ee310e5dac3cac0c067ce05f48fbfbf96a21092

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - watchfiles >=1.0.4,<2.0.0
    - jupyverse-api >=0.12.0,<0.13.0

tests:
  - python:
      imports:
        - fps_file_watcher
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: An FPS plugin for the file watcher API
  description: An FPS plugin for the file watcher API
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/plugins/file_watcher

extra:
  recipe-maintainers:
    - davidbrochart
